### PR TITLE
set class-attribute from Object or Array values

### PR DESCRIPTION
**Pull request by mindplay-dk**
Add support for initializing the class-attribute from a map where class-name maps to `true`/`false` values, or from an Array of class-names.

This is very common and very widely-used feature in most JSX-based libraries - it gets a bit cumbersome to handhold this for every view implementation, and this shouldn't add much to the minified footprint, I think?

### CODE REVIEW

**Comment by JorgeBucaran** [comment]
@mindplay-dk At first glance this seems like the kind of thing you get by using https://github.com/JorgeBucaran/classcat or JedWatson/classNames yes?

**Comment by mindplay-dk** [comment]
I guess, though both of these do more than just join class-names?

Makes me wonder if we ought to put property-setters in a map and expose it? If we could plug in custom property-setters, people could choose from these packages, for example. (I'd also like to have support for e.g. `data` and the `on`-attribute that most JSX frameworks support, at some point - I find these are all the "bare bones" no-brainer features that everyone needs. "batteries included.")

Though in the case of the class-attribute, IMO, it's common enough to include by default - practically everyone would need to install and plug in another package for this.

**Comment by JorgeBucaran** [comment]
@mindplay-dk I think this is not acceptable for picodom. I don't expect picodom to be used for building frontend apps; I didn't build it for that. I expect picodom to be used as a building block to create lightweight JS frameworks, very much like Hyperapp.

**Comment by mindplay-dk** [comment]
> I expect picodom to be used as a building block to create lightweight JS frameworks

I get it! "wrong layer", right? Things like class-name transformations and other property/attribute magic, I can absolutely implement in a higher-level layer that makes these transformations *before* passing them to picodom. Gotcha :-)

What this doesn't address though, is the difference between properties and attributes - the need to know or decide which you're updating.

DOM elements ultimately are a duality: the objects have a set of properties *and* a set of attributes - unfortunately, JSX only has one syntax for attributes, so we need to address this somehow.

Currently, the VDOM model doesn't allow you to distinguish between properties and attributes, at all. That's a problem - if I'm building a micro framework on top of pico, I don't have any control over properties and attributes individually.

We should open a new issue to discuss this further maybe?

**Comment by mindplay-dk** [comment]
I've opened a separate issue, so I'm closing this one.

**Comment by JorgeBucaran** [comment]
@mindplay-dk Yeah, let's open a new issue to discuss this very interesting topic. I have a few opinions on the subject! 🙏

**Comment by JorgeBucaran** [comment]
@mindplay-dk You already opened it! https://github.com/picodom/picodom/issues/56 :)

**Pull request closed without merging**
